jobs:
  build-on-linux:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source code
      uses: actions/checkout@v1
      with:
        ref: master
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package
  build-on-windows:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source code
      uses: actions/checkout@v1
      with:
        ref: master
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package
  deploy-snapshots:
    needs:
    - build-on-linux
    - build-on-windows
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source code
      uses: actions/checkout@v1
      with:
        ref: master
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      name: deploy snapshots to sonatype
      run: 'mvn -s .mvn/settings.xml -Dmaven.test.skip=true deploy

        '
name: CI build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
