jobs:
  release:
    name: Release new version
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source code
      uses: actions/checkout@v2
      with:
        ref: master
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      env:
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      name: Publish new version
      run: 'git config user.name "Mahmoud Ben Hassine"

        git config user.email "mahmoud.benhassine@icloud.com"

        export GPG_TTY=$(tty)

        echo "${{ secrets.GPG_SECRET }}" | gpg --batch --import

        echo "${{ secrets.GPG_PUBLIC }}" | gpg --batch --import

        mvn -B -s .mvn/settings.xml release:prepare release:perform -Dmaven.test.skip=true
        -Darguments=-Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}

        '
name: Release to Maven Central
on:
  repository_dispatch:
    types: trigger-ga___release.yml
